version: '3'
services:
  database:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movies_api
      MYSQL_USER: movies_api
      MYSQL_PASSWORD: password123
